<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DefineConstants>UNITY_ANDROID</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/SolarNet.Core/SolarNet.Core.csproj" />
    <Compile Include="../../Packages/com.hoonex.solarnet/Runtime/Android/*.cs" />
    <Compile Include="UnityEngineStubs.cs" />
  </ItemGroup>
</Project>
